-- CreateEnum
CREATE TYPE "JobCategory" AS ENUM ('IT', 'SALES', 'MARKETING', 'FINANCE', 'DESIGN', 'MANAGEMENT', 'LOGISTICS', 'HEALTHCARE', 'EDUCATION', 'HOSPITALITY', 'OTHER');

-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "category" "JobCategory" NOT NULL DEFAULT 'OTHER';
